/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ArmsRouteImport } from './routes/arms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MotorIdRouteImport } from './routes/motor.$id'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmsRoute = ArmsRouteImport.update({
  id: '/arms',
  path: '/arms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorIdRoute = MotorIdRouteImport.update({
  id: '/motor/$id',
  path: '/motor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arms': typeof ArmsRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/test': typeof TestRoute
  '/motor/$id': typeof MotorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arms': typeof ArmsRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/test': typeof TestRoute
  '/motor/$id': typeof MotorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arms': typeof ArmsRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/test': typeof TestRoute
  '/motor/$id': typeof MotorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arms'
    | '/logs'
    | '/settings'
    | '/system'
    | '/test'
    | '/motor/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arms' | '/logs' | '/settings' | '/system' | '/test' | '/motor/$id'
  id:
    | '__root__'
    | '/'
    | '/arms'
    | '/logs'
    | '/settings'
    | '/system'
    | '/test'
    | '/motor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmsRoute: typeof ArmsRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  SystemRoute: typeof SystemRoute
  TestRoute: typeof TestRoute
  MotorIdRoute: typeof MotorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arms': {
      id: '/arms'
      path: '/arms'
      fullPath: '/arms'
      preLoaderRoute: typeof ArmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motor/$id': {
      id: '/motor/$id'
      path: '/motor/$id'
      fullPath: '/motor/$id'
      preLoaderRoute: typeof MotorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmsRoute: ArmsRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  SystemRoute: SystemRoute,
  TestRoute: TestRoute,
  MotorIdRoute: MotorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
